apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: home-assistant
  namespace: home-assistant
spec:
  destination:
    namespace: home-assistant
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd
    repoURL: https://github.com/kevchu3/home-assistant-k8s.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
